### ISSUE TITLE
[Feat] 홈뷰 터치영역 변경

### ISSUE THREAD

**Issue by jumining** [Team-Smeme/Smeem-iOS#130]
## Issue

 홈뷰 터치영역 변경

## To-do

- [x] 한국어로 일기 작성하기, 영어로 일기 작성하기 터치 영역 (라벨->버튼) 크기에 맞춰 터치 영역 조정
- [x] 전체 보기 버튼 클릭시 (일기 상세 뷰->일기 전체 영역) 클릭시 일기 상세 뷰 이동으로 터치 영역 조정
- [x] 홈에 있는 마이페이지 버튼 크기 조정
