### ISSUE TITLE
[Fix] 24.12.10 QA

### ISSUE THREAD

**Issue by joonBaek12** [Team-Smeme/Smeem-iOS#241]
## To-do

- [ ] 세그멘트 컨트롤 글씨 깨짐
- [x] 래핑뷰들 네비게이션 스택 이슈
- [x] 완벽한 문장 filter
- [ ] 바텀 시트 연동
