### ISSUE TITLE
[Feat] 홈뷰->다른뷰 이동 구현

### ISSUE THREAD

**Issue by jumining** [Team-Smeme/Smeem-iOS#73]
## Issue

홈뷰->다른뷰 이동 구현
## To-do

- [x] 마이페이지
- [x] 일기 상세 조회
- [x] 한국어 일기 쓰기
- [x] 외국어 일기 쓰기
