### ISSUE TITLE
[Chore] QA 반영

### ISSUE THREAD

**Issue by joonBaek12** [Team-Smeme/Smeem-iOS#77]
## Issue

QA 반영합니다.
## To-do

- [x] 랜덤주제, 힌트버튼, 랜덤주제 새로고침 이미지 추가 및 할당
- [x] step1-> step2 데이터 전달
- [ ] [작성 완료] 토스트 팝업
- [x] 한국어 일기 작성하기 화면 전환
- [x] 랜덤주제 줄 수에 따라 Height값 변환
- [ ] 작성조건 수정 (영어, 특수문자 다 허용)
- [ ] 키보드 올라갔을 때 BottomViewHeight 조절
- [x] 토스트 메시지 키보드 올라갔을 때는 키보드 위에서 뜨게 수정
- [x] 일기 상세보기 뷰 수정, 삭제 버튼
- [x] 삭제 클릭 시 '일기를 삭제할까요?' 팝업
- [ ] 일기 작성시 랜덤주제 id값 같이 전달
