### ISSUE TITLE
[Chore] qa 반영2

### ISSUE THREAD

**Issue by joonBaek12** [Team-Smeme/Smeem-iOS#84]
## To-do

- [x] DiaryKoreanView leftButtonDidTap 화면전환 로직 관련 처리
- [x] 키보드 올라갔을 때 BottomViewHeight 조절
- [x] RandomSubjectView lineBreakMode -> byWordWrapping
- [ ] [작성 완료] 토스트 팝업
- [x] [상세보기]YYYY년 MM월 DD일 HH:MM AM/PM 으로 표기되는가
